version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-sports_platform}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    networks:
      - sports_platform_network

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-sports_platform}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sports_platform_network

volumes:
  postgres_data:

networks:
  sports_platform_network:
    driver: bridge